### PR TITLE
Support for various accelerometer configurations

### PR DESCRIPTION
**Pull request by pelikhan**
Project settings allow to pick accelerometer.
image

### CODE REVIEW

**Comment by jamesadevine** [comment]
Can you select more than one accelerometer for use in the project? In that case what happens?

**Comment by pelikhan** [comment]
We determine the type of accelerometer at runtime using the whoAmI answer.

**Comment by jamesadevine** [comment]
And you expect the user to know the model of the accelerometer?

**Comment by pelikhan** [comment]
Good point.... we are also running out of flash space and these get linked.

**Comment by pelikhan** [comment]
@mmoskal we could also turn them on individually. For boards like CPX, we know which one but for other boards like Metro, it would come from the breadboard.

**Comment by mmoskal** [comment]
I think detecting at runtime is fine for arcade, since it has quite a bit of flash and we want portable binaries, but for maker it should be selected at runtime. Can be done with that package config defines.

**Comment by pelikhan** [comment]
should be selected at "compile" time?

**Comment by mmoskal** [comment]
Are we short on flash on SAMD21? I thought we were around 120k and these are 256k?

Blue pill is another story.

**Pull request merged**
