### PR TITLE
disable webusb

### PR DESCRIPTION
**Pull request by pelikhan**

### CODE REVIEW

**Comment by Cinbarker** [comment]
Hi Pelikhan! 
Thanks for your work on this awesome web app. 
I was wondering what the plans are for the webusb functionality. Will the direct uploading and console being disabled as well?
Thank you
-Cinbarker

**Comment by pelikhan** [comment]
We don't have the bandwith currently to work on webusb for maker -- unfortunately. @mmoskal is this something we can investigate?

**Comment by pelikhan** [comment]
@Cinbarker may i ask how you use maker?

**Comment by Cinbarker** [comment]
@pelikhan Thanks for the response. I teach my students robotics using makecode, and especially the console feature was a great simple replacement for a serial monitor.

**Comment by pelikhan** [comment]
which board are you using? i can reenable webusb.

**Comment by Cinbarker** [comment]
@pelikhan Sorry for the late response! I saw webusb was re-enabled, thank you for that. I am currently working on making a custom editor using pxt for my students. If I may ask, why was the webusb removed in the first place? It sometimes acts up for me, but are there known issues with it?

**Comment by pelikhan** [comment]
I have been doing work on WebUSB for Microbit and I’ve broken a bit the experience in maker right now. I’ve unbroken it and reenabled it.

The WebUSB experience is still annoying becuSe the editor complains that the device is disconnected after flashing. I’ll get to fixing this eventually.

**Comment by Cinbarker** [comment]
Oh ok, that’s good to know. I agree that the “device not properly ejected” error can be confusing. The main issue I’m trying to address in my version of it is devices randomly not being found with webusb when code is already running. It’s a shame the reliability of this new protocol seems difficult to work with. Thank you again for your work on this! Most of this stuff goes over my head, but I’d love to get it working since it has so much potential!

**Pull request merged**
